2024-11-27 02:24:04,065 --- WARNING --- Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\ivan\PycharmProjects\pythonProject\module_12\module_12_4\tests_12_4.py", line 28, in test_run
    run_2 = rt.Runner(123)
            ^^^^^^^^^^^^^^
  File "C:\Users\ivan\PycharmProjects\pythonProject\module_12\module_12_4\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-27 02:24:04,066 --- WARNING --- "Неверная скорость для Runner"
Traceback (most recent call last):
  File "C:\Users\ivan\PycharmProjects\pythonProject\module_12\module_12_4\tests_12_4.py", line 17, in test_walk
    run_1 = rt.Runner('runner',-5 )
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ivan\PycharmProjects\pythonProject\module_12\module_12_4\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
